### PR TITLE
DPI issue fix and few MainForm changes

### PR DESCRIPTION
**Pull request by Jaex**
I was just going fix DPI issue but later saw ShareX logo looks weird centered, so for it to be consistent with puush header, added ShareX header image. But then bottom panels was not looking good with that header image so did few changes to them. But I followed your rules about it being simple and I think how it shows progress now is more simpler than before.

Commit messages contains more info about this pull request.

### CODE REVIEW

**Comment by peppy** [comment]
The new logo looks out of place and ugly :-1:

**Comment by Jaex** [comment]
What if I remove logo completely? Because previous one looks weird too centered.

**Comment by peppy** [comment]
can i just leave it how it is

**Comment by Jaex** [comment]
Sure. Added previous logo now:

**Comment by peppy** [comment]
New installer has been pushed live :+1:.

**Pull request merged**
